[features]
seeds = false
skip-lint = false
testing = ["prisoners_arena/testing"]

[programs.localnet]
prisoners_arena = "7gJU56iACgPLsinhLCc2cSZs7ZuwSs1fHgFeDNdnZxSX"

[programs.devnet]
prisoners_arena = "7gJU56iACgPLsinhLCc2cSZs7ZuwSs1fHgFeDNdnZxSX"

[programs.mainnet]
prisoners_arena = "7gJU56iACgPLsinhLCc2cSZs7ZuwSs1fHgFeDNdnZxSX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/prisoners-arena"]
